version: '3.8'

services:
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: models_auditory
    volumes:
      - .:/models_auditory
    ports:
      - "8000:8000"