# Generated by Django 5.0.1 on 2024-02-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.TextField()),
                ("model", models.TextField()),
                ("model_instance_id", models.IntegerField()),
                ("data_before_change", models.JSONField()),
                ("data_after_change", models.JSONField()),
            ],
            options={
                "db_table": "auditory_model",
            },
        ),
        migrations.CreateModel(
            name="ModelOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_1", models.DateField()),
                ("field_2", models.DateField(null=True)),
                ("field_3", models.TextField()),
                (
                    "field_4",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                ("field_5", models.BooleanField()),
                ("field_6", models.BooleanField()),
                ("field_7", models.BooleanField()),
                ("field_8", models.BooleanField()),
                ("field_9", models.BooleanField()),
                ("field_10", models.BooleanField()),
                ("field_11", models.BooleanField()),
                ("field_12", models.BooleanField()),
                ("field_13", models.BooleanField()),
                ("field_14", models.BooleanField()),
                ("field_15", models.BooleanField()),
            ],
            options={
                "db_table": "model_one",
            },
        ),
        migrations.CreateModel(
            name="ModelTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_1", models.DateField()),
                ("field_2", models.DateField(null=True)),
                ("field_3", models.TextField()),
                (
                    "field_4",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                ("field_5", models.BooleanField()),
                ("field_6", models.BooleanField()),
                ("field_7", models.BooleanField()),
                ("field_8", models.BooleanField()),
                ("field_9", models.BooleanField()),
                ("field_10", models.BooleanField()),
                ("field_11", models.BooleanField()),
                ("field_12", models.BooleanField()),
                ("field_13", models.BooleanField()),
                ("field_14", models.BooleanField()),
                ("field_15", models.BooleanField()),
            ],
            options={
                "db_table": "model_two",
            },
        ),
    ]
